spring.application.name=NexUs-Auth
spring.config.import=optional:file:.env.properties
app.api-key=${API_KEY}
spring.flyway.lock-retry-count=10
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true