spring.application.name=NexUs-Auth
spring.config.import=optional:file:.env.properties
app.api-key=${API_KEY}
spring.flyway.lock-retry-count=10
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.health.mail.enabled=false

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

app.tracing-access-key=${TRACING_ACESS:}